name: ds_ads
description: Ads components for sect.dev (https://sect.dev/)
version: 0.3.0
repository: https://github.com/al-tush/ds_ads

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fimber: ^0.6.6

  ds_common: ^0.1.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  collection: ^1.16.0

  google_mobile_ads: ">=1.3.0 <4.0.0"

  applovin_max: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: pro.altush.ads.ds_ads
        pluginClass: DsAdsPlugin
